#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

#find . -type f -name 'log.*' -delete
runApplication ./Allclean

runApplication decomposePar

# Example with runParallel to run in parallel
# getApplication finds solver name from "application" entry in controlDict
runParallel "$(getApplication)"

runApplication reconstructPar

#------------------------------------------------------------------------------
